### ISSUE TITLE
Grunt task named "htmlImproved"

### ISSUE THREAD

**Issue by masterbee** [nidorx/grunt-html-improved#1]
Hi @nidorx,
First and foremost great work on this module it is nice to see and this module really makes things very flexible for the developer without having to learn an new syntax like Jade or Handlebars to work with HTML files. 

That said, I was wondering why you named the grunt task  for this module `htmlImproved`? Would not `html-improved` be more intuitive? 

I am using a common grunt module _load-grunt-config_ which allows me to break up my grunt file into sub files of the grunt folder. I have to use the  registered grunt task name as the file name for everything to work and as you can imagine this makes the file name fall out of norm with other grunt modules.

I know it is really a small change but would love to see it, since it appeases the purist side of me on file naming conventions of things.

**Comment by nidorx** [comment]
Hi @masterbee, I'm sorry for the delay in response.

The current name is fully compatible with "load-grunt-config".

I had left the project a little side but I'll be back as soon as possible to work on it to make some improvements.

**Gruntfile.js**

``` js
module.exports = function (grunt) {

    // Load grunt tasks automatically
    require('load-grunt-config')(grunt, {
        //init: true
    });
};
```

**grunt/aliases.yaml**

``` yaml
dev:
  - 'htmlImproved'
```

**grunt/htmlImproved.js**

``` js
module.exports = {
    dev: {
        options: {
            defaultVars: function () {
                return {
                    package: require('./package.json'),
                    project: require('./project.json')
                };
            }
        },
        files: [
            {
                expand: true,
                cwd: '<%= settings.src %>',
                src: [
                    '**/*.html',
                    '!vendor/**/*.html'
                ],
                dest: '<%= settings.dev %>'
            }
        ]
    }
};
```

**command line**

``` bash
grunt dev

Running "htmlImproved:dev" (htmlImproved) task
>> 1 file created.

Done, without errors.
```
